#!/bin/sh

## General ---------------------------------------------------#

# Run java applications without issues
export _JAVA_AWT_WM_NONREPARENTING=1

## Configurations --------------------------------------------#

workspaces() {
	name=1
	for monitor in `bspc query -M`; do
		bspc monitor ${monitor} -n "$name" -d 'I' 'II' 'III' 'IV' 'V'
		let name++
	done
}
workspaces

# Window information
bspc config border_width 0 
bspc config window_gap 8
bspc config pointer_follows_monitor true
bspc config focus_follows_pointer true

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false

## Window rules ----------------------------------------------#

# remove all rules first
bspc rule -r *:*


## Autostart -------------------------------------------------#

pgrep -x sxhkd > /dev/null || sxhkd &		# Start shortcuts
pkill picom					# Kill picom
picom--experimental-backends 			# Restart picom

#dunst &
#udiskie &
#flameshot &

feh --bg-fill ~/Pictures/wallpaper		# Set wallpaper
#~/.config/polybar/launch.sh			# Start polybar
