#!/bin/sh

# Autostart
pgrep -x sxhkd > /dev/null || sxhkd &		# Start shortcuts
pkill picom					# Kill picom
picom & 					# picom --experimental-backends &	# Restart picom
feh --bg-fill ~/Pictures/wallpaper		# Set wallpaper
#~/.config/polybar/launch.sh			# Start polybar

# Monitor
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# Window information
bspc config border_width 0 
bspc config window_gap 9
bspc config pointer_follows_monitor true
bspc config focus_follows_pointer true

# Rules
# bspc rule -a mumble state=floating follow=on focus=on
